version: "3.7"

services:
  bazarr:
    image: linuxserver/bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./.bazarr/config:/config
      - ${PLEX_MOVIES_DIR}:/movies
      - ${PLEX_TV_DIR}:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  heimdall:
    image: linuxserver/heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./.heimdall/config:/config
    ports:
      - 80:80
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./.jackett/config:/config
    ports:
      - 9117:9117
    restart: unless-stopped
    
  ombi:
    image: linuxserver/ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./.ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VERSION=docker
    volumes:
      - ./.plex/config:/config
      - ${PLEX_MOVIES_DIR}:/movies
      - ./.plex/transcode:/transcode
      - ${PLEX_TV_DIR}:/tv
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./.radarr/config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${PLEX_MOVIES_DIR}:/movies
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:preview
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./.sonarr/config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${PLEX_TV_DIR}:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
