version: "2"
services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ~/.bazarr/config:/config
      - ${PLEX_MOVIES_DIR}:/movies
      - ${PLEX_TV_DIR}:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ~/.heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - RUN_OPTS=run options here #optional
    volumes:
      - ~/.jackett/config:/config
      # - path to blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - BASE_URL=/ombi #optional
    volumes:
      - ~/.ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
  openvpn-as:
    image: linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - INTERFACE=eth0 #optional
    volumes:
      - ~/.openvpn-as/config:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - TZ=${TZ}
    volumes:
      - ~/.plex/config:/config
      - ${PLEX_DIR}:/data
      - ~/.plex/transcode:/transcode
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ~/.radarr/config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${PLEX_MOVIES_DIR}:/movies
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ~/.sonarr/config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${PLEX_TV_DIR}:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
      - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true
    volumes:
      - ~/.transmission/config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ~/.transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
