version: "3.7"

services:
  transmission:
    image: linuxserver/transmission
    env_file:
      - torrent.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${TRANSMISSION_DIR}/config:/config
      - ${TRANSMISSION_DOWNLOADS_DIR}:/downloads
    ports:
      - 9092:9091
      - ${TRANSMISSION_PORT}:${TRANSMISSION_PORT}
      - ${TRANSMISSION_PORT}:${TRANSMISSION_PORT}/udp
    restart: unless-stopped

  transmission-rss:
    build:
      context: ./transmission-rss
      dockerfile: Dockerfile
      args:
        - UID=${PUID}
        - GID=${PGID}
    env_file:
      - torrent.env
    volumes:
      - ${TRANSMISSION_RSS_DIR}/config/transmission-rss.conf:/etc/transmission-rss.conf
    restart: unless-stopped
