version: "3.7"

services:
  openvpn:
    image: giggio/openvpn-arm
    cap_add:
      - NET_ADMIN
    volumes:
      - ${VPN_DATA_DIR}/openvpn/config:/etc/openvpn
    ports:
      - ${OPENVPN_PORT}:1194/udp
    restart: unless-stopped