version: "3.7"

services:
  bazarr:
    image: linuxserver/bazarr:development
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./.bazarr/config:/config
      - ${PLEX_MOVIES_DIR}:/movies
      - ${PLEX_TV_DIR}:/tv
    expose:
      - 6767
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./.jackett/config:/config
    expose:
      - 9117
    restart: unless-stopped
    
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- VIRTUAL_HOST=${OMBI_HOST}
      #- VIRTUAL_PORT=3579
      #- LETSENCRYPT_HOST=${OMBI_HOST}
      #- LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./.ombi/config:/config
    expose:
      - 3579
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    network_mode: host
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ./.plex/config:/config
      - ${PLEX_MOVIES_DIR}:/movies
      - ${PLEX_PREROLLS_DIR}:/prerolls
      - /dev/shm:/transcode
      - ${PLEX_TV_DIR}:/tv
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./.radarr/config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${PLEX_MOVIES_DIR}:/movies
    expose:
      - 7878
    networks:
      - torrent_default
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./.sonarr/config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${PLEX_TV_DIR}:/tv
    expose:
      - 8989
    networks:
      - torrent_default
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - .tautulli/config:/config
      - .plex/config/Library/Application Support/Plex Media Server/Logs:/logs
    expose:
      - 8181
    restart: unless-stopped

networks:
  torrent_default:
    external: true
