version: "3.7"

services:
  transmission:
    image: linuxserver/transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${TORRENT_DATA_DIR}/transmission/config:/config
      - ${TRANSMISSION_DOWNLOADS_DIR}:/downloads
      - ${TRANSMISSION_DOWNLOADS_ALT_DIR}:/downloads-alt
    ports:
      - 9092:9091
      - ${TRANSMISSION_PORT_2}:${TRANSMISSION_PORT_2}
      - ${TRANSMISSION_PORT_2}:${TRANSMISSION_PORT_2}/udp
    restart: unless-stopped

  transmission-rss:
    build:
      context: ./transmission-rss
      dockerfile: Dockerfile
      args:
        - UID=${PUID}
        - GID=${PGID}
    volumes:
      - ${TORRENT_DATA_DIR}/transmission-rss/config/transmission-rss.conf:/etc/transmission-rss.conf
    restart: unless-stopped
